import Head from "next/head"; // for Google fonts
import styles from "../styles/Home.module.css";

import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zoltans Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>
      <Navbar />
      <main className={styles.main}></main>
    </>
  );
}
