import Head from "next/head"; // for Google fonts

export default function Home() {
  return (
    <>
      <Head>
        <title>Zoltans Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          crossOrigin="true"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <section>
        <h1>Home</h1>
      </section>
    </>
  );
}
